apiVersion: v1
kind: Namespace
metadata:
  name: doomwar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: doomwar
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Doom War - zespół 31</title>
    </head>
    <body><h1>Doom War (zespół 31): REPLACEME</h1></body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-html
  namespace: doomwar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static-html
  template:
    metadata:
      labels:
        app: nginx-static-html
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static-html
  namespace: doomwar
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx-static-html
