apiVersion: v1
kind: Namespace
metadata:
  name: ogloszenia-krytyczne
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: GGORG0+Potyczki25Zespol31@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: ogloszenia-krytyczne
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Oficjalne Komunikaty</title>
    </head>
    <body><h1>Wszystko pod kontrolą. Wróg w odwrocie!</h1></body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ogloszenia-krytyczne
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ogloszenia-krytyczne
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: ogloszenia-krytyczne
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: ogloszenia-krytyczne.193.187.67.105.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
  tls:
    - hosts:
        - ogloszenia-krytyczne.193.187.67.105.sslip.io
      secretName: ogloszenia-krytyczne-tls
